dist: trusty
language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - cmake
    - lua5.2
    - libjson-c-dev
    - liblua5.2-dev
script:
- cmake . -DBUILD_LUA=OFF
- make -j1
- make package
deploy:
  provider: releases
  api_key:
    secure: syqU2fT1vGbdA5WrvtvgeIburxffJK4s3hE42Fmu7T1xr875iZtCzTp21ImD2JatJFhTdJrRtxQZRe0QViXkTiOJBqIaR0JMB++FMJOyEifkK3hjBhsA0aTuXeLL5OmpF3pXYvoKM3DYw+wkTe5khKFbc5VTvIX7yVaXw5vVLjfWHOW6TtKzoepFoRv0ceHbLmOUv5IxEhhsoaCuUMMvocQ5lUk/dZfayeyuAHzD4aLpG3oQPdgGC50jj/A8LGqLOa1BnmIGgPG8BBLcAAFtjkFUn87Ed0RIOFVGn03uZ7VZsCOVMXNISWHhsmVIOTeU+dzZEFH4FjD9IcrsSu2vbAFMSvfDL3qN3nDM3uzF5usgHPTVVJAbYPAqAWCMT043kUP98Nk7I28LxYmBKmUuEMcfMJdOkF3j9fI2+Qn69y6eBX8c5dyauIL1qAqOVS27fX1hx1yEZksET13NE31ghA4yjwLTXcZKJa1uwf5E96M8ifIEupfSNPO1S3hy8TpNdRMc1jSSurEz6U4om2G1vhiKmO9KqpeuYZQFrbsDLHtlyZmhbhkl7R4oLeG7b0K3bx1TXxzGHD/j8I3octJ8ktqs2JMyIioEuaCKmn9arN5Nefjz0e4cF7tkHFABN3bO9RE31BHI3i7JerQlkVn8nAX4GfzX6xWb3j5Hv9SlA7k=
  file: ubox-1.0-Linux.deb
  skip_cleanup: true
  on:
    tags: true 
