dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    packages:
    - cmake
    - lua5.2
    - libjson-c-dev
    - liblua5.2-dev
    
script:
- cmake . -DBUILD_LUA=OFF
- make -j1
- make package
